on:
  push:
    branches: 
      - main
    paths-ignore: # dont run when changes made to these folders 
      - '.vscode/**'
jobs:
  build-vsix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install deps 
        uses: npm install @vscode/vsce
      - name: Package VS Code extension
        id: package
        uses: nhedger/package-vscode-extension@v1
      
      - name: Publish VS Code extension artifact
        uses: actions/upload-artifact@v4
        with:
            name: injected-erb
            path: ${{ steps.package.outputs.packagePath }}
